language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
before_install:
    - cd frontend
    - "npm config set spin false"
    - npm i -g vercel
install:
    - npm install
script:
    - npm run test
    - npm run build
deploy:
    provider: script
    script: bash script/deploy.sh
    skip_cleanup: true
