language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
before_install:
    - cd frontend
    - "npm config set spin false"
install:
    - npm install
    - npm update
script:
    - npm run build
