POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"thongdev@restaskest.com",
    "password":"thongdev"
}


###
DELETE http://localhost:5000/api/chat/5e534ef362aaf85216b52ff7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDc0YmY0MjY1ZGZiMzBiOTBhNGY1ZiIsImlhdCI6MTU4MjUxODA5MiwiZXhwIjoxNTgyNTIxNjkyfQ.Y13JEJVB7ojvIV0Op88F7UQQrR9qVwbUD89EFbIzKME

###
GET http://localhost:5000/api/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDc0YmY0MjY1ZGZiMzBiOTBhNGY1ZiIsImlhdCI6MTU4MjUxODA5MiwiZXhwIjoxNTgyNTIxNjkyfQ.Y13JEJVB7ojvIV0Op88F7UQQrR9qVwbUD89EFbIzKME





