POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"thongdev@restaskest.com",
    "password":"thongdev"
}

###
GET http://localhost:5000/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDc0YmY0MjY1ZGZiMzBiOTBhNGY1ZiIsImlhdCI6MTU4MTczMjEwNCwiZXhwIjoxNTgxNzM1NzA0fQ.S6HoGHH2J5xCzKxus7l546RIDm-62Vua93LyUCP1aaw